### ISSUE TITLE
Possible Open Source?

### ISSUE THREAD

**Issue by yossev** [AhmedHosny2/Student-Guide#2]
The Website is Great!

Great work for the team working on it, _Huge_ amount of effort can be seen by just browsing.

I was Wondering if eligible students can work on tasks/new features regarding this website 

The team could make a trello board/ or maybe Submit new issues with _new features_ tag

Id Love to contribute! Thanks

**Comment by AhmedHosny2** [comment]
Thank you for your kind words! We're glad you like the website. We're open to contributions from eligible students like you. We'll consider setting up a Trello board or using GitHub issues for new features. Feel free to share your ideas or submit a GitHub issue. Looking forward to potentially working together!!
